[project]
name = "philosopy"
version = "0.1.0"
description = "a python api to get famous philosophers quotes"
readme = "README.md"
requires-python = ">=3.14"

dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.139.2",
    "httpx>=0.28.1",
    "pydantic-settings>=2.14.2",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.22",
    "sqlmodel>=0.0.39",
    "taskipy>=1.14.1",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.ruff]
line-length = 79
exclude = [
    "alembic/",
    "app/models/"
]

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = 'single'

[tool.pytest.ini_options]
pythonpath = "."
addopts = '-p no:warnings'
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.taskipy.tasks]
lint = 'uv run ruff check'
format = 'uv run ruff format'
server = 'uv run fastapi dev'
test = 'pytest -s -x --cov=app -vv'
